apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaConnectServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.kafkaConnectServicePort }}
  selector:
    app: {{ .Values.kafkaConnectService.selectorLabelValue }}
