#namespace: ""
kafkaConfigName: "kafka-tools-config"
data: {}
schemaRegistryServiceName: "kafka-schema-registry"
#schemaRegistryServicePort: 8081
schemaRegistryExternalServiceName: "kafka-schema-registry-external"
kafkaSchemaRegistryStatefulSetName: "kafka-schema-registry"
kafkaSchemaRegistryStatefulSet:
  dependencyAnnotation: "\"\""
kafkaSchemaRegistryStatefulSetContainerName: "kafka-schema-registry"
#env:
#  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 
#  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 
