apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeperHeadlessServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: client
    port: {{ .Values.clientPort }}
  - name: peer
    port: {{ .Values.peerPort }}
  - name: leader-election
    port: {{ .Values.leaderElectPort }}
  selector:
    app: zookeeper
    storage: persistent
