apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeperServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: client
    port: {{ .Values.clientPort }}
  selector:
    app: zookeeper
