apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restProxyServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.restProxyPort }}
  selector:
    app: rest-proxy