apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaRegistryExternalServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.schemaRegistryServicePort }}
    protocol: TCP
    targetPort: {{ .Values.schemaRegistryServicePort }}
  selector:
    app: schema-registry
