apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaRegistryServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.schemaRegistryServicePort }}
  selector:
    app: schema-registry
