apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: broker
    port: {{ .Values.brokerPort }}
  selector:
    app: kafka
