{{- if eq .Values.enableUi true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaConnectUiServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: connect-ui
{{- end }}
