apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerCredSecretName }}
  namespace: {{ .Values.kafkaNameSpace }}
type: kubernetes.io/dockerconfigjson
data:
  {{- toYaml .Values.data | nindent 2 }}